import { SignInButton, SignUpButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import LoadingPage from "./loading";

export default function Home() {
  const { isLoaded, isSignedIn } = useUser();
  const router = useRouter();

  useEffect(() => {
    if (isSignedIn) {
      void router.replace("/dashboard");
    }
  }, [isLoaded, isSignedIn, router]);

  if (!isLoaded) {
    return <LoadingPage />;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen items-center justify-center">
        <div className="flex min-h-screen items-center justify-center">
          <div className="flex flex-col items-center rounded-md border p-4">
            <h3 className="text-lg font-semibold">
              Welcome to management task online !!
            </h3>
            <div className="space-x-4">
              <SignInButton forceRedirectUrl={"/dashboard"}>
                <button>Sign In</button>
              </SignInButton>
              <SignUpButton signInForceRedirectUrl={"/dashboard"}>
                <button>Sign Up</button>
              </SignUpButton>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
